#!/usr/bin/env bash
#Copyright (C) 2015  Helal Uddin <helal00 at gmail.com>
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

_srcsbinpath=$(dirname $(readlink -f $0))

if [ ! -d "$_srcsbinpath/.store" ] ; then
	echo "The prgram is not yet ready to run. Please run $_srcsbinpath/syncprep first." 1>&2
	exit 1
fi

#write out current crontab
crontab -l > $_srcsbinpath/.store/mycron
if grep -q "$_srcsbinpath/runsyncer" $_srcsbinpath/.store/mycron ; then
	grep -v "$_srcsbinpath/runsyncer" $_srcsbinpath/.store/mycron > $_srcsbinpath/.store/mycronnew
	#install new cron file
	crontab $_srcsbinpath/.store/mycronnew
	echo "$_srcsbinpath/runsyncer removed from crontab!!"
else
	echo "$_srcsbinpath/runsyncer doesn't exist in crontab!!"
fi
rm -rf $_srcsbinpath/.store/mycron
rm -rf $_srcsbinpath/.store/mycronnew
