#!/usr/bin/env bash
#Copyright (C) 2015  Helal Uddin <helal00 at gmail.com>
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

_srcsbinpath=$(dirname $(readlink -f $0))
_geturl=""
if [ ! -z "$1" ] && [ "${1,,}" = "url" ] ; then
	_geturl="url"
	shift
fi
_getboth=""
if [ ! -z "$1" ] && [ "${1,,}" = "both" ] ; then
	_getboth="both"
	shift
fi
if [ -z "$1" ] ; then
	echo "No url given" 1>&2
	exit 1
fi
_baseurl="$1"

function strtoarry(){
	local _str _retarray _deli _c _l;_str=$1 _retarray=$2 _deli=$3
	_c=-1;while read -r _l; do _c=$((_c+1));eval $_retarray[$_c]='$_l';done <<< "$(echo $_str | sed -e "s/$_deli/\n/g")"
}


_scheme=${_baseurl%%://*}
_scheme=${_scheme,,}
_url=${_baseurl#*://}

strtoarry "$_url" "_uparts" '\/'
if [ ${#_uparts[@]} -lt 3 ] ; then
	echo "Incomplete url given : $_url. Alteast the url should have http(s)://host/user/repo format" 1>&2
	exit 1
fi

_host="github.com"
_user=${_uparts[1]}
_user=${_user,,}
_repo=${_uparts[2]}
_repo=${_repo,,}

_finalbaseurl="$_scheme://$_host/$_user/$_repo/releases"

_thepat="\"\/.*\/.*\/releases\/tag\/.*\""
_latestTag=$(wget -qO - "$_finalbaseurl" | grep -o $_thepat | head -1 | awk -F"/" '{print $NF}')
if [ ! -z "$_latestTag" ] ; then
	_latestTag=${_latestTag::-1}
	_dlurl="$_scheme://$_host/$_user/$_repo/archive/${_latestTag}.tar.gz"
	#echo "$_latestTag"
	#printf "${_latestTag//\%/\\x}"
	if [ -z "$_geturl" ] || [ ! -z "$_getboth" ] ; then
		printf "${_latestTag//\%/\\x}\n"
	else	
		printf "${_dlurl//\%/\\x}\n"
	fi
	if [ ! -z "$_getboth" ] ; then
		printf "${_dlurl//\%/\\x}\n"
	fi
fi
