#!/usr/bin/env bash
#Copyright (C) 2015  Helal Uddin <helal00 at gmail.com>
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

_srcsbinpath=$(dirname $(readlink -f $0))
_srchomepath=$(dirname $_srcsbinpath)

if [ ! -d "$_srcsbinpath/.store" ] ; then
	echo "The prgram is not yet ready to run. Please run $_srcsbinpath/syncprep first." 1>&2
	exit 1
fi

_logpath="$_srchomepath/sync.log"

_verbose=$1
if [ ! -z "$_verbose" ] && [ "$_verbose" = "show" ] ; then
	_logcmd=""
else
	_logcmd="&>>$_logpath"
fi

_maxsize=1048576
_running=0
if [ -f $_srcsbinpath/.store/syncer.pid ] ; then
	_runningpid=$(cat $_srcsbinpath/.store/syncer.pid)
	kill -0 $_runningpid 2>/dev/null
	if [ $? -eq 0 ] ; then
		_running=1
	fi
fi

if [ "$_running" -eq 0 ] && [ -f "$_logpath" ] ; then
	_actualsize=$(du -k "$_logpath" | cut -f 1)
	if [ $_actualsize -ge $_maxsize ]; then
	    rm -rf $_logpath.bak
	    mv $_logpath $_logpath.bak
	fi
fi


eval "$_srcsbinpath/syncer ${_logcmd}"
