#!/usr/bin/env bash
#Copyright (C) 2015  Helal Uddin <helal00 at gmail.com>
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

_srcsbinpath=$(dirname $(readlink -f $0))
_srchomepath=$(dirname $_srcsbinpath)

if [ ! -d "$_srcsbinpath/.store" ] ; then
	echo "The prgram is not yet ready to run. Please run $_srcsbinpath/syncprep first." 1>&2
	exit 1
fi

if [ -s "$_srcsbinpath/.store/binpaths.ok" ] ; then
	. $_srcsbinpath/.store/binpaths.ok		
fi

if [ -s "$_srcsbinpath/functions" ] ; then
	. $_srcsbinpath/functions
else
	echo "$_srcsbinpath/functions file not found!" 1>&2
	exit 1
fi

if [ ! -z "$_go"  ] || _go=$(isinstalled "go" "$_go") ; then
	_insatlledver=$($_go version | awk '{print $3}')
	_latestversion=$("$_githublatest" https://github.com/golang/go)
	if [ "$_insatlledver" != "$_latestversion" ] ; then
		echo "	INFORMATION: Newer version of go language avaibale. You have version: $_insatlledver and version available: $_latestversion. Check http://golang.org/doc/install for more detials, if you wish to upgrade go language."
	fi
fi

if [ ! -z "$_skicka"  ] || _skicka=$(isinstalled "skicka" "$_skicka") ; then
    if [ -d $_srchomepath/old_skicha_src ] ; then
        mv $_srchomepath/old_skicha_src $_srchomepath/old_skicha_src_$(date +%s)
    fi
    mv $GOPATH/src/github.com/google/skicka $_srchomepath/old_skicha_src
	$_go get "github.com/google/skicka"
fi
